# Generated by Django 5.0.3 on 2024-03-10 11:57

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0004_recruiter_seeker_job_delete_seekermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seekermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('degree', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('usertype', models.CharField(choices=[('seeker', 'Seek'), ('recruiter', 'Recruit')], default='seeker', max_length=60)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.DeleteModel(
            name='Seeker',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
