# Generated by Django 5.0.3 on 2024-03-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0005_seekermodel_remove_job_recruiter_delete_seeker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('jobtitle', models.CharField(max_length=50)),
                ('jobdesp', models.CharField(max_length=250)),
                ('skillsreq', models.CharField(max_length=50)),
                ('businessadd', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruitermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('degree', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('skills', models.CharField(max_length=250)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('usertype', models.CharField(choices=[('seeker', 'Seeker'), ('recruiter', 'Recruit')], default='recruiter', max_length=60)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
