# Generated by Django 5.0.3 on 2024-03-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0006_jobmodel_recruitermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitermodel',
            old_name='degree',
            new_name='businessname',
        ),
        migrations.RenameField(
            model_name='recruitermodel',
            old_name='experience',
            new_name='businesstype',
        ),
        migrations.RemoveField(
            model_name='recruitermodel',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='recruitermodel',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='recruitermodel',
            name='skills',
        ),
    ]
