# Generated by Django 5.0.3 on 2024-05-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0007_rename_degree_recruitermodel_businessname_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seekermodel',
            managers=[
            ],
        ),
    ]
