# Generated by Django 5.0.3 on 2024-05-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0008_alter_seekermodel_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekermodel',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
