# Generated by Django 5.0.3 on 2024-05-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0009_alter_seekermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitermodel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='recruitermodel',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='seekermodel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='seekermodel',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
