# Generated by Django 5.0.3 on 2024-08-19 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0012_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='recruiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seekerapp.recruitermodel'),
            preserve_default=False,
        ),
    ]
