# Generated by Django 5.0.3 on 2024-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekerapp', '0014_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume/'),
        ),
    ]
